feat: build with Dune Package Management
Signed-off-by: Etienne Marais <dev@maiste.fr>

diff --git a/.github/workflows/binary.yaml b/.github/workflows/binary.yaml
--- a/.github/workflows/binary.yaml
+++ b/.github/workflows/binary.yaml
@@ -2,8 +2,8 @@ name: Binaries
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: '0 1 * * *' # Triggers the build at 1:00 UTC time
+  # schedule:
+  #   - cron: '0 1 * * *' # Triggers the build at 1:00 UTC time
 
 jobs:
   binary:
@@ -16,12 +16,12 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - os: macos-13
-            name: x86_64-apple-darwin
-            installable: .#dune-experimental
-          - os: macos-14
-            name: aarch64-apple-darwin
-            installable: .#dune-experimental
+          # - os: macos-13
+          #   name: x86_64-apple-darwin
+          #   installable: .#dune-experimental
+          # - os: macos-14
+          #   name: aarch64-apple-darwin
+          #   installable: .#dune-experimental
           - os: ubuntu-22.04
             name: x86_64-unknown-linux-musl
             installable: .#dune-static-experimental
@@ -71,114 +71,143 @@ jobs:
 
 
 
-  check-artifacts:
-    strategy:
-        fail-fast: false
-        matrix:
-          include:
-            - os: macos-13
-              name: x86_64-apple-darwin
-            - os: macos-14
-              name: aarch64-apple-darwin
-            - os: ubuntu-22.04
-              name: x86_64-unknown-linux-musl
+  # check-artifacts:
+  #   strategy:
+  #       fail-fast: false
+  #       matrix:
+  #         include:
+  #           - os: macos-13
+  #             name: x86_64-apple-darwin
+  #           - os: macos-14
+  #             name: aarch64-apple-darwin
+  #           - os: ubuntu-22.04
+  #             name: x86_64-unknown-linux-musl
+  #
+  #   runs-on: ${{ matrix.os }}
+  #   needs: binary
+  #   steps:
+  #
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #
+  #     - uses: actions/download-artifact@v4
+  #
+  #     - name: Get dune accessible
+  #       run: |
+  #         mv ./${{ matrix.name }}/dune ./dune
+  #         chmod u+x ./dune
+  #
+  #     - name: Check dune is working
+  #       run: |
+  #           export PATH="$PWD:$PATH"
+  #           cd test
+  #           dune pkg lock
+  #           dune build
 
-    runs-on: ${{ matrix.os }}
+  build_with_dune:
     needs: binary
-    steps:
-
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - uses: actions/download-artifact@v4
-
-      - name: Get dune accessible
-        run: |
-          mv ./${{ matrix.name }}/dune ./dune
-          chmod u+x ./dune
-
-      - name: Check dune is working
-        run: |
-            export PATH="$PWD:$PATH"
-            cd test
-            dune pkg lock
-            dune build
-
-
-
-  deploy-s3:
     runs-on: ubuntu-latest
-    needs: [binary, check-artifacts]
-    permissions:
-      contents: write
     steps:
-
-      - name: Install rclone
-        run: |
-          sudo -v ; curl https://rclone.org/install.sh | sudo bash
-
-      - name: Prepare SSH env
-        shell: bash
-        run: |
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/tarides
-          echo "$SSH_PUBLIC_KEY" > ~/.ssh/tarides.pub
-          chmod 600 ~/.ssh/tarides
-          chmod 600 ~/.ssh/tarides.pub
-          ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
-        env:
-          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
-
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Setup OCaml with cache
-        uses: ocaml/setup-ocaml@v3
-        with:
-          ocaml-compiler: "5.2"
-          dune-cache: true
-
-      - name: Install Sandworm
-        run: cd sandworm && opam install -y . --deps-only && opam exec  -- dune build
 
       - uses: actions/download-artifact@v4
         with:
           path: /home/runner/artifacts
 
+      - name: Add Dune to path
+        run: |
+          mkdir -p $HOME/.local/bin
+          cp $HOME/artifacts/x86_64-unknown-linux-musl/dune $HOME/.local/bin/
+          chmod u+x $HOME/.local/bin/dune
+
+      - name: Check Dune version
+        run: dune --version
+
       - name: Move artifacts to scope
         run: mv "/home/runner/artifacts" "."
 
-      - name: Export Rclone configuration
-        run: echo "${{ secrets.RCLONE_CONF }}" >> rclone.conf
+      - name: Locking file
+        run: cd sandworm && dune pkg lock
 
-      - name: Export executables and generate html
-        shell: bash
-        run: ./sandworm/_build/install/default/bin/sandworm sync --commit "${{ needs.binary.outputs.git-commit }}"
+      - name: Building the project
+        run: cd sandworm && dune build
 
 
-      - name: Commit changes to branch
-        run: |
-          git config --global user.name 'Sandworm'
-          git config --global user.email 'tarides@users.noreply.github.com'
-          (git add index.html metadata.json && \
-          git commit -m "Nightly build $(date +'%Y-%m-%d')" && \
-          git push) || echo "No new data" # Prevent from committing empty stuff
 
-  notify:
-    runs-on: ubuntu-latest
-    needs: [ binary, check-artifacts, deploy-s3 ]
-    if: ${{ !cancelled() && (needs.binary.result == 'failure' || needs.check-artifacts.result == 'failure' || needs.deploy-s3.result == 'failure' ) }}
-    steps:
-      - name: Post an error message to Slack
-        id: slack
-        uses: slackapi/slack-github-action@v1.27.0
-        with:
-          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
-          slack-message: |
-            :red_circle: I'm sorry to bother you, but it seems your build is failing:
-            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+  # deploy-s3:
+  #   runs-on: ubuntu-latest
+  #   needs: [binary, check-artifacts]
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #
+  #     - name: Install rclone
+  #       run: |
+  #         sudo -v ; curl https://rclone.org/install.sh | sudo bash
+  #
+  #     - name: Prepare SSH env
+  #       shell: bash
+  #       run: |
+  #         mkdir -p ~/.ssh
+  #         echo "$SSH_PRIVATE_KEY" > ~/.ssh/tarides
+  #         echo "$SSH_PUBLIC_KEY" > ~/.ssh/tarides.pub
+  #         chmod 600 ~/.ssh/tarides
+  #         chmod 600 ~/.ssh/tarides.pub
+  #         ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
+  #       env:
+  #         DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
+  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
+  #
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Setup OCaml with cache
+  #       uses: ocaml/setup-ocaml@v3
+  #       with:
+  #         ocaml-compiler: "5.2"
+  #         dune-cache: true
+  #
+  #     - name: Install Sandworm
+  #       run: cd sandworm && opam install -y . --deps-only && opam exec  -- dune build
+  #
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         path: /home/runner/artifacts
+  #
+  #     - name: Move artifacts to scope
+  #       run: mv "/home/runner/artifacts" "."
+  #
+  #     - name: Export Rclone configuration
+  #       run: echo "${{ secrets.RCLONE_CONF }}" >> rclone.conf
+  #
+  #     - name: Export executables and generate html
+  #       shell: bash
+  #       run: ./sandworm/_build/install/default/bin/sandworm sync --commit "${{ needs.binary.outputs.git-commit }}"
+  #
+  #
+  #     - name: Commit changes to branch
+  #       run: |
+  #         git config --global user.name 'Sandworm'
+  #         git config --global user.email 'tarides@users.noreply.github.com'
+  #         (git add index.html metadata.json && \
+  #         git commit -m "Nightly build $(date +'%Y-%m-%d')" && \
+  #         git push) || echo "No new data" # Prevent from committing empty stuff
 
+  # notify:
+  #   runs-on: ubuntu-latest
+  #   needs: [ binary, check-artifacts, deploy-s3 ]
+  #   if: ${{ !cancelled() && (needs.binary.result == 'failure' || needs.check-artifacts.result == 'failure' || needs.deploy-s3.result == 'failure' ) }}
+  #   steps:
+  #     - name: Post an error message to Slack
+  #       id: slack
+  #       uses: slackapi/slack-github-action@v1.27.0
+  #       with:
+  #         channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
+  #         slack-message: |
+  #           :red_circle: I'm sorry to bother you, but it seems your build is failing:
+  #           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #       env:
+  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+  #
