tmp: check artifacts

diff --git a/.github/workflows/binary.yaml b/.github/workflows/binary.yaml
--- a/.github/workflows/binary.yaml
+++ b/.github/workflows/binary.yaml
@@ -180,95 +180,95 @@ jobs:
           # mv "x86_64-unknown-linux-musl/$ARCHIVE_TARGZ" .
           tar -xvf "x86_64-unknown-linux-musl/$ARCHIVE_TARGZ"
           echo "$PWD/x86_64-unknown-linux-musl/$ARCHIVE_DIR" >> "$GITHUB_PATH"
-          echo "PATH is $GITHUB_PATH"
+          echo "PATH is $PATH"
           # mv "./$ARCHIVE_DIR/dune" ./dune.exe
 
       - name: Check Dune version
         run: |
-          echo "GITHUB PATH is $GITHUB_PATH"
+          echo "PATH is $PATH"
           dune --version
 
       - name: Building the project
         run: dune build
 
-  deploy-s3:
-    runs-on: ubuntu-latest
-    needs: [binary, check-artifacts]
-    permissions:
-      contents: write
-    steps:
-      - name: Install rclone
-        run: |
-          sudo -v ; curl https://rclone.org/install.sh | sudo bash
-
-      - name: Prepare SSH env
-        shell: bash
-        run: |
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/tarides
-          echo "$SSH_PUBLIC_KEY" > ~/.ssh/tarides.pub
-          chmod 600 ~/.ssh/tarides
-          chmod 600 ~/.ssh/tarides.pub
-          ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
-        env:
-          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
-
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup OCaml with cache
-        uses: ocaml/setup-ocaml@v3
-        with:
-          ocaml-compiler: "5.2"
-          dune-cache: true
-
-      - name: Update config on test
-        if: ${{ github.ref == 'refs/heads/staging' }}
-        run: |
-          sed -i 's#let bucket_dir = .*#let bucket_dir = "/dune/test"#g' ./bin/config.ml
-          sed -i 's#let url = .*#let url = "https://get.dune.build/test"#g' ./bin/config.ml
-          git add --ignore-errors ./bin/config.ml
-          cat ./bin/config.ml
-
-      - name: Install Sandworm deps && build
-        run: opam install -y . --deps-only && opam exec -- dune build
-
-      - uses: actions/download-artifact@v4
-        with:
-          path: /home/runner/artifacts
-
-      - name: Move artifacts to scope
-        run: mv "/home/runner/artifacts" "."
-
-      - name: Export Rclone configuration
-        run: echo "${{ secrets.RCLONE_CONF }}" >> rclone.conf
-
-      - name: Export executables and generate html
-        shell: bash
-        run: opam exec -- dune exec sandworm -- sync --commit "${{ needs.binary.outputs.git-commit }}"
-
-      - name: Commit changes to branch
-        run: |
-          git config --global user.name 'Sandworm'
-          git config --global user.email 'ocaml-dune@users.noreply.github.com'
-          (git add metadata.json && \
-          git commit -m "Nightly build $(date +'%Y-%m-%d')" && \
-          git push) || echo "No new data" # Prevent from committing empty stuff
-
-  notify:
-    runs-on: ubuntu-latest
-    needs: [binary, check-artifacts, deploy-s3]
-    if: ${{ github.ref == 'refs/heads/main' && !cancelled() && (needs.binary.result == 'failure' || needs.check-artifacts.result == 'failure' || needs.deploy-s3.result == 'failure' ) }}
-    steps:
-      - name: Post an error message to Slack
-        id: slack
-        uses: slackapi/slack-github-action@v1.27.0
-        with:
-          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
-          slack-message: |
-            :red_circle: I'm sorry to bother you, but it seems your build is failing:
-            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+  # deploy-s3:
+  #   runs-on: ubuntu-latest
+  #   needs: [binary, check-artifacts]
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #     - name: Install rclone
+  #       run: |
+  #         sudo -v ; curl https://rclone.org/install.sh | sudo bash
+  #
+  #     - name: Prepare SSH env
+  #       shell: bash
+  #       run: |
+  #         mkdir -p ~/.ssh
+  #         echo "$SSH_PRIVATE_KEY" > ~/.ssh/tarides
+  #         echo "$SSH_PUBLIC_KEY" > ~/.ssh/tarides.pub
+  #         chmod 600 ~/.ssh/tarides
+  #         chmod 600 ~/.ssh/tarides.pub
+  #         ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
+  #       env:
+  #         DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
+  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
+  #
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Setup OCaml with cache
+  #       uses: ocaml/setup-ocaml@v3
+  #       with:
+  #         ocaml-compiler: "5.2"
+  #         dune-cache: true
+  #
+  #     - name: Update config on test
+  #       if: ${{ github.ref == 'refs/heads/staging' }}
+  #       run: |
+  #         sed -i 's#let bucket_dir = .*#let bucket_dir = "/dune/test"#g' ./bin/config.ml
+  #         sed -i 's#let url = .*#let url = "https://get.dune.build/test"#g' ./bin/config.ml
+  #         git add --ignore-errors ./bin/config.ml
+  #         cat ./bin/config.ml
+  #
+  #     - name: Install Sandworm deps && build
+  #       run: opam install -y . --deps-only && opam exec -- dune build
+  #
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         path: /home/runner/artifacts
+  #
+  #     - name: Move artifacts to scope
+  #       run: mv "/home/runner/artifacts" "."
+  #
+  #     - name: Export Rclone configuration
+  #       run: echo "${{ secrets.RCLONE_CONF }}" >> rclone.conf
+  #
+  #     - name: Export executables and generate html
+  #       shell: bash
+  #       run: opam exec -- dune exec sandworm -- sync --commit "${{ needs.binary.outputs.git-commit }}"
+  #
+  #     - name: Commit changes to branch
+  #       run: |
+  #         git config --global user.name 'Sandworm'
+  #         git config --global user.email 'ocaml-dune@users.noreply.github.com'
+  #         (git add metadata.json && \
+  #         git commit -m "Nightly build $(date +'%Y-%m-%d')" && \
+  #         git push) || echo "No new data" # Prevent from committing empty stuff
+  #
+  # notify:
+  #   runs-on: ubuntu-latest
+  #   needs: [binary, check-artifacts, deploy-s3]
+  #   if: ${{ github.ref == 'refs/heads/main' && !cancelled() && (needs.binary.result == 'failure' || needs.check-artifacts.result == 'failure' || needs.deploy-s3.result == 'failure' ) }}
+  #   steps:
+  #     - name: Post an error message to Slack
+  #       id: slack
+  #       uses: slackapi/slack-github-action@v1.27.0
+  #       with:
+  #         channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
+  #         slack-message: |
+  #           :red_circle: I'm sorry to bother you, but it seems your build is failing:
+  #           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #       env:
+  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
